class ErrorCode:
    AUTHENTICATION_REQUIRED = "Authentication required."
    AUTHORIZATION_FAILED = "Authorization failed. User has no access."
    INVALID_TOKEN = "Invalid token."
    INVALID_CREDENTIALS = "Invalid credentials."
    EMAIL_TAKEN = "Email is already taken."
    USERNAME_TAKEN = "Username is already taken."
    REFRESH_TOKEN_NOT_VALID = "Refresh token is not valid."
    REFRESH_TOKEN_REQUIRED = "Refresh token is required either in the body or cookie."
    USER_NOT_FOUND = "User not found"
    USER_BANNED = "User is banned to use the app."
    INVALID_API_KEY = "Invalid API key."
    TOKEN_EXPIRED = "Token expired"
    ACTION_NOT_ALLOWED = "This action not allowed"
    SETTING_ROLE_NOT_ALLOWED = "You're not allowed to set the role"
    USER_ALREADY_EXISTS = "A user with this username already exists"
